esphome:
  name: tdr-soil-sensor-on-esp32
  includes:
   
  libraries:
    - Wire
    - EspSoftwareSerial
    
    
  
 


external_components:
  - source: 
      type: local
      path: components
    components: [tdr_soil_sensor]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Bbox-727DF9A6"
  password: "c7HwHdEL33bhCJ4fVm"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:


### RS485 
#Using the UART interface as RS485
#uart:

 # id: modbus_serial
 # rx_pin: 1
#  tx_pin: 2
 # baud_rate: 4800
#  stop_bits: 1

# Attach the UART interace to the modbus interface
#modbus:
#  id: modbus1
 # uart_id: modbus_serial



tdr_soil_sensor:
  - id: TDR0
    pin_tx: 12 # tx pin for the UART 
    pin_rx: 13 # rx pin for the UART
    pin_de: 4
    pin_re: 0
    update_interval: 10s # update interval of the measurement 
    temperature: # Soil temperature in degree 
      name: "Soil temperature"
      accuracy_decimals: 1

    humidity: # Soil humidity in %
      name: "Soil humidity"
      accuracy_decimals: 1
    
    ec: # Soil EC
      name: "Soil EC"
      accuracy_decimals: 1
    
    pore_water: # Soil EC
      name: "Soil pore water EC"
      accuracy_decimals: 1
    
    bulk_permittivity: # Soil bulk permittivity
      name: "Soil bulk permittivity"
      accuracy_decimals: 1
    
    
    #pin: 35  # ADC pin Connected to the PH Sensor . Pay attention some ADC pin are used by the ESP32 and using them will generate a conflit.
    #acid_voltage: 2032.44     # Calibration for Acid solution (4.0)
    #neutral_voltage: 1500.0   # Calibration for Neutral solution (7.0)
    #temperature: 25 
    
    #calibration_mode: # Switch to select calibration mode 
    #  name: "Calibration mode"
    #number_of_samples: 10 # [1-50] Number of samples for the moving average calculation
    #ph_sensor: # The PH sensor holding the read value
    #  name: "PH sensor 1"
    #  accuracy_decimals: 1
    


#sensors:
web_server:
  port: 80
