esphome:
  name: esp32-for-digital-pump
  includes:
   
  libraries:
    - ESP32Servo
    - SPI
    - Wire 
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit ADS1X15
    
    
  
 


external_components:
  - source: 
      type: local
      path: components
    components: [DFRobot_ads1115_ec, ads1115_adc]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:

# external ADC 
ads1115_adc:
  - id: External_ADC
    sda: 25
    scl: 26
    address: 0x68


DFRobot_ads1115_ec:
  - id: PH1
    id_ads1115: External_ADC  # Attach the external ADC to the PH Sensor
    channel: 0  # ADC channel of the ADS1115 [0 - 3]
    kvalue_low: 1     # Calibration for Kvalue HIGH
    kvalue_high: 1  # Calibration for Kvalue LOW
    temperature: 25 
    update_interval: 10s # update interval of the EC measurement 
    calibration_mode: # Switch to select calibration mode 
      name: "Calibration mode"
    ph_sensor: # The PH sensor holding the read value
      name: "PH sensor 1"
      accuracy_decimals: 1
    

#sensors:
web_server:
  port: 80
