esphome:
  name: esp32-for-digital-pump
  includes:
   
  libraries:
    - ESP32Servo
    
  
 


external_components:
  - source: 
      type: local
      path: components
    components: [digital_pump]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:


digital_pump:
  - id : Pump1
    pin: 2
    doser_on: # switch for the doser
      name: "Doser ON"
    dose: # Number for the dose in (L)
      name: "Pump 1 dose (L)"
      mode: box
      min_value: 0
      max_value: 1000
    calibration: # Number for the dose calibration (L/s)
      name: "Pump 1 Calibration (L/s)"
      mode: box
      min_value: 0
      max_value: 100000

#sensors:
web_server:
  port: 80
